/* eslint-disable @next/next/next-script-for-ga */
var dataLayer: any[];

export default function Head(argumentsDataObject: any) {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      {/* <script
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-K6MBY9B33E"
      ></script>

      <script>
        window.dataLayer = window.dataLayer || []; function
        gtag()dataLayer.push(argumentsDataObject); gtag('js', new Date());
        gtag('config', 'G-K6MBY9B33E')
      </script> */}
    </>
  );
}
